export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const signupConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE"
}

export const newsletterConstants = {
    NEWSLETTER_REQUEST: "NEWSLETTER_REQUEST",
    NEWSLETTER_SUCCESS: "NEWSLETTER_SUCCESS",
    NEWSLETTER_FAILURE: "NEWSLETTER_FAILURE"
}

export const queryConstants = {
    QUERY_REQUEST: "QUERY_REQUEST",
    QUERY_SUCCESS: "QUERY_SUCCESS",
    QUERY_FAILURE: "QUERY_FAILURE"
}

export const quoteConstants = {
    QUOTE_REQUEST: "QUOTE_REQUEST",
    QUOTE_SUCCESS: "QUOTE_SUCCESS",
    QUOTE_FAILURE: "QUOTE_FAILURE"
}