import Two_wheeler from '../../img/Vehicles/Two_wheeler.jpg'
import Three_wheeler from '../../img/Vehicles/Three_wheeler.jpg'

const Data={
    "data" : [
        {
            id: 1,
            
            category:"two-wheeler-loan",
            url: "Why-to-take-Two-Wheeler-loan-from-Yuwan-Finance",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Two_wheeler,
            alt:"Two Wheeler",
            name:"Why to take Two Wheeler loan from Yuwan Finance",
           description:"Director of Yuwan Finance",
           date:"19 Aug 2021"
        },
        {
            id: 2,
            category:"two-wheeler-loan",
            url: "How-can-we-apply-for-Two-Wheeler-Loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Two_wheeler,
            alt:"Two Wheeler",
            name:"How can we apply for Two Wheeler Loan",
           description:"Director of Yuwan Finance",
           date:"19 Aug 2021"
        },
        {
            id: 3,
            category:"two-wheeler-loan",
            url: "How-to-take-two-wheeler-loan-in-easy-steps",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Two_wheeler,
            alt:"Two Wheeler",
            name:"How to take Two Wheeler loan in easy steps",
           description:"Director of Yuwan Finance",
           date:"19 Aug 2021"
        },
        {
            id: 4,
            category:"two-wheeler-loan",
            url: "How-to-pay-EMI-of-two-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Two_wheeler,
            alt:"Two Wheeler",
            name:"How to pay EMI of two wheeler loan",
           description:"Director of Yuwan Finance",
           date:"19 Aug 2021"
        },
        {
            id: 5,
            category:"two-wheeler-loan",
            url: "How-to-contact-for-two-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Two_wheeler,
            alt:"Two Wheeler",
            name:"How to contact for two wheeler loan",
           description:"Director of Yuwan Finance",
           date:"19 Aug 2021"
        },
        {
            id: 6,
            category:"three-wheeler-loan",
            url:"three-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Three_wheeler,
            alt:"Two Wheeler",
            name:"Two Wheeler",
           description:"Director of Yuwan Finance",
            
        },
        {
            id: 7,
            category:"three-wheeler-loan",
            url:"three-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Three_wheeler,
            alt:"Two Wheeler",
            name:"Two Wheeler",
           description:"Director of Yuwan Finance",
        },
        {
            id: 8,
            category:"three-wheeler-loan",
            url:"three-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Three_wheeler,
            alt:"Two Wheeler",
            name:"Two Wheeler",
           description:"Director of Yuwan Finance",
        },
        {
            id: 9,
            category:"three-wheeler-loan",
            url:"three-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Three_wheeler,
            alt:"Two Wheeler",
            name:"Two Wheeler",
           description:"Director of Yuwan Finance",
        },
        {
            id: 10,
            category:"three-wheeler-loan",
            url:"three-wheeler-loan",
            imageclass:"image",
            image_imgclass:"image__img",
            contentclass:"image__overlay",
            nameclass:"image__title",
            descriptionclass:"image__description",
            img: Three_wheeler,
            alt:"Two Wheeler",
            name:"Two Wheeler",
           description:"Director of Yuwan Finance",
        }
    ]
}
export default Data;